services:
  php:
    build:
      context: ./php
    environment:
      - PROJECT_NAME=${PROJECT_NAME:-portofolio}
      - XDEBUG=${XDEBUG:-false}
    volumes:
      - ./src:/var/www/html
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  db:
    image: mariadb:10.11
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_DATABASE: ${PROJECT_NAME:-portofolio}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-p455w0rd}
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
